#[features]
#seeds = false
#skip-lint = false
[programs.localnet]
mlm_system = "EuuVAbcqK268gEjAoSKHkrG9nCpbmooYqYXfcndbFHdn"

#[registry]
#url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "/home/vasilisa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
